adding @types/glob was necessary to avoid a tsc error because of presence of higher version glob in top-level node_modules
    > @elastic/opentelemetry-instrumentation-openai@0.2.0 compile
    > tsc -p .

    ../../node_modules/@types/glob/index.d.ts:29:42 - error TS2694: Namespace '".../node_modules/minimatch/dist/commonjs/index"' has no exported member 'IOptions'.

    29     interface IOptions extends minimatch.IOptions {
                                                ~~~~~~~~

    ../../node_modules/@types/glob/index.d.ts:74:30 - error TS2724: '".../node_modules/minimatch/dist/commonjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?

    74         minimatch: minimatch.IMinimatch;
                                    ~~~~~~~~~~

    Found 2 errors.

I love TS.