this test fixture uses tsc, add an explicit devDep on typescript to have it
This is a flail to deal with a failure of bootstrap-in-code.test.js:246 with Node.js 20.6.0 in CI only

not ok 7 "npm install && npm run compile" succeeded (took 1.414s)
  ---
    operator: error
    at: <anonymous> (/home/runner/work/elastic-otel-node/elastic-otel-node/packages/opentelemetry-node/test/bootstrap-in-code.test.js:246:15)
    stack: |-
      Error: Command failed: npm install && npm run compile
      node:internal/errors:496
          ErrorCaptureStackTrace(err);
          ^
      TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /usr/local/lib/node_modules/typescript/bin/tsc. Loading extensionless files is not supported inside of "type":"module" package.json contexts. The package.json file /usr/local/lib/node_modules/typescript/package.json caused this "type":"module" context. Try changing /usr/local/lib/node_modules/typescript/bin/tsc to have a file extension. Note the "bin" field of package.json can point to a file with an extension, for example {"type":"module","bin":{"tsc":"./bin/tsc.js"}}